telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 136, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 21, in greet_user
    1/0
ZeroDivisionError: division by zero
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\telegram\ext\dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "C:\Python34\lib\site-packages\telegram\ext\commandhandler.py", line 136, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 21, in greet_user
    1/0
ZeroDivisionError: division by zero
telegram.ext.updater - ERROR - Error while getting Updates: Timed out
telegram.ext.updater - WARNING - Exiting immediately!
